
#pragma once


//UIÏûÏ¢     
struct ST_UI_MSG
{
	DWORD dwDialogId;
	DWORD dwControlId;
	UINT msg;
	WPARAM wParam;
	LPARAM lParam;
};




//button×´Ì¬
enum BUTTON_MOUSE_FLAG
{
	BUTTON_MOUSE_NORMAL = 0,
	BUTTON_MOUSE_ON,
	BUTTON_MOUSE_DOWN,
};


/////////////////////////////////////////////
//TextureId
namespace UI_TEXTURE_ID
{
	enum COMMON_TEXTURE_ID
	{
		COMMON_TEX_WHITE,

		COMMON_TEX_BUTTON_OK_NORMAL,
		COMMON_TEX_BUTTON_OK_ON,
		COMMON_TEX_BUTTON_OK_DOWN,

		COMMON_TEX_BUTTON_CANCEL_NORMAL,
		COMMON_TEX_BUTTON_CANCEL_ON,
		COMMON_TEX_BUTTON_CANCEL_DOWN,

		COMMON_TEX_LOADING_BACK,
		COMMON_TEX_LOADING_LOADING,
		
		GAMEUI_TEX_ITEM_STATIC_BUTTON_NORMAL,
		GAMEUI_TEX_ITEM_STATIC_BUTTON_DOWN,
		GAMEUI_TEX_ITEM_STATIC_BUTTON_ON,

		MAX_COMMON_TEX_NUM,
	};

	enum LOGINUI_TEXTURE_ID
	{
		LOGINUI_TEX_LOGIN_BACK = 0,
		LOGINUI_TEX_LOGIN_LOG,

		LOGINUI_TEX_SELCHAR_BACK,
		LOGINUI_TEX_SELCHAR_BACK2,
		LOGINUI_TEX_SELCHAR_CHAR_BACK1,
		LOGINUI_TEX_SELCHAR_CHAR_BACK2,
		LOGINUI_TEX_SELCHAR_BUTTON_ENTER_NORMAL,
		LOGINUI_TEX_SELCHAR_BUTTON_ENTER_ON,
		LOGINUI_TEX_SELCHAR_BUTTON_ENTER_DOWN,
		LOGINUI_TEX_SELCHAR_BUTTON_LEFT_ON,
		LOGINUI_TEX_SELCHAR_BUTTON_LEFT_DOWN,
		LOGINUI_TEX_SELCHAR_BUTTON_RIGHT_ON,
		LOGINUI_TEX_SELCHAR_BUTTON_RIGHT_DOWN,

		MAX_LOGINUI_TEX_NUM,
	};

	enum GAMEUI_TEXTURE_ID
	{
		GAMEUI_TEX_ITEM_STATIC_BACK,
		GAMEUI_TEX_ITEM_STATIC_0,
		GAMEUI_TEX_ITEM_STATIC_1,
		GAMEUI_TEX_ITEM_STATIC_2,
		GAMEUI_TEX_ITEM_STATIC_3,
		GAMEUI_TEX_ITEM_STATIC_4,
		GAMEUI_TEX_ITEM_STATIC_5,
		GAMEUI_TEX_ITEM_STATIC_6,

		GAMEUI_TEX_PLAYER_STATIC_BACK,
		GAMEUI_TEX_PLAYER_STATIC_PLAYER,
		GAMEUI_TEX_PLAYER_STATIC_HP,
		GAMEUI_TEX_PLAYER_STATIC_MP,

		GAMEUI_TEX_SYSTEM_BACK,
	
		GAMEUI_TEX_SYSTEM_BUTTON_NORMAL,
		GAMEUI_TEX_SYSTEM_BUTTON_DOWN,
		GAMEUI_TEX_SYSTEM_BUTTON_ON,

		GAMEUI_TEX_ITEM_BUTTON_NORMAL,
		GAMEUI_TEX_ITEM_BUTTON_DOWN,
		GAMEUI_TEX_ITEM_BUTTON_ON,

		GAMEUI_TEX_SHOP_STATIC_BACK,

		GAMEUI_TEX_FLX_STATIC_ITEM,

		GAMEUI_TEX_SKILL_STATIC_BACK,
		GAMEUI_TEX_SKILL_STATIC_ALPHASKILL,
		
		GAMEUI_TEX_FLX_STATIC_LOAD,
		GAMEUI_TEX_FLX_STATIC_LOADING,

		GAMEUI_TEX_SKILL_STATIC_1,
		GAMEUI_TEX_SKILLBOOKUI_STATIC_BACK,
		GAMEUI_TEX_MOUSEMESSAGE_STATIC_BACK,

		GAMEUI_TEX_SKILL_STATIC_2,

		GAMEUI_TEX_MINIMAP_STATIC_BACK,
		GAMEUI_TEX_MINIMAP_STATIC_MAP,
		GAMEUI_TEX_MINIMAP_STATIC_ROLE,

		GAMEUI_TEX_ITEM_BUTTON_ITEMBUTTON_NORMAL,
		GAMEUI_TEX_ITEM_BUTTON_ITEMBUTTON_DOWN,
		GAMEUI_TEX_ITEM_BUTTON_ITEMBUTTON_ON,

		GAMEUI_TEX_SKILL_STATIC_BUTTONRECT,

		GAMEUI_TEX_SKILL_BUTTON_FIXDOWN,
		GAMEUI_TEX_SKILL_BUTTON_NULLDOWN,
		GAMEUI_TEX_SKILL_BUTTON_SKILLBOOKDOWN,
		GAMEUI_TEX_SKILL_BUTTON_SKILLBOOKNORMAL,


		MAX_GAMEUI_TEX_NUM,
	};
}




////////////////////////////////////////////
//UI_ID
enum BASEUI_ID
{
	BASEUI_LOGIN = 0,
	BASEUI_GAME,
	MAX_BASEUI_NUM,
};


enum UI_LOGIN_DIALOG_ID
{
	UI_LOGIN_DIALOG_LOGIN = 0,
	UI_LOGIN_DIALOG_SELSERVER,
	UI_LOGIN_DIALOG_SELCHAR,
	UI_LOGIN_DIALOG_CREATECHAR,
	MAX_LOGIN_DIALOG_NUM,
};

enum UI_GAME_DIALOG_ID
{
	UI_GAME_DIALOG_ITEM = 0,
	UI_GAME_DIALOG_PLAYER,
	UI_GAME_DIALOG_MONSTER,
	UI_GAME_DIALOG_SYSTEM,
	UI_GAME_DIALOG_SHOP,
	UI_GAME_DIALOG_FLX,
	UI_GAME_DIALOG_SKILL,
	UI_GAME_DIALOG_SKILLBOOK,
	UI_GAME_DIALGO_MOUSEMESSAGE,
	UI_GAME_DIALGO_MINIMAP,

	MAX_GAME_DIALOG_NUM,
};

enum UI_DIALOG_ID
{
	UI_DIALOG_LOADING = 10000,
	UI_DIALOG_MOUSE,
};

enum MSG_TYPE
{
	BUTTON_CLICK = 0x0f01,
};