//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ImageBoard.rc
//
#define IDC_RESET                       3
#define IDD_ABOUTBOX                    100
#define IDC_AVAIL_MEM                   101
#define IDC_EDIT                        102
#define IDC_PHYSICAL_MEM                102
#define IDC_AVAIL_VIRTUAL_MEM           103
#define IDC_CPU                         104
#define IDC_OS                          105
#define IDC_VERSION                     106
#define IDD_ABOUTDLG                    107
#define IDB_SPLASH                      108
#define IDR_MAINFRAME                   128
#define IDR_IMAGEBTYPE                  129
#define IDD_GAMMA                       130
#define IDR_PAINTTOOL                   131
#define IDD_GRAY                        131
#define IDD_COLOR                       132
#define IDD_PAINTPARAM                  133
#define IDD_EXPOSURE                    134
#define IDC_CURSORFREELINE              136
#define IDD_BC                          136
#define IDC_CURSORFILL                  137
#define IDD_COLORBITS                   137
#define IDC_CURSORMOVE                  138
#define IDD_SELECTPASTE                 138
#define IDD_PENWIDTH                    139
#define IDD_CANVASSIZE                  140
#define IDD_EMBOSSMENT                  141
#define IDC_CURSORPICKER                142
#define IDD_SPREAD                      142
#define IDC_CURSORGENERALDRAW           144
#define IDC_CURSORCURVE                 145
#define IDD_SCALE                       146
#define IDR_TEXTTOOL                    147
#define IDD_CONVOLUTE                   147
#define IDC_CURSORERASER                152
#define IDD_JPEGFORMAT                  154
#define IDD_LOADTIF                     159
#define IDD_ROTATEANGLE                 160
#define IDB_BLANK                       162
#define IDB_PHOTO                       163
#define IDS_LENGTH_UNIT_PIXEL           1000
#define IDC_EDIT1                       1000
#define IDS_LENGTH_UNIT_INCH            1001
#define IDC_HEIGHT                      1001
#define IDC_EDIT2                       1001
#define IDS_LENGTH_UNIT_MM              1002
#define IDC_EDIT3                       1002
#define IDS_BITCOUNT_1                  1003
#define IDC_RADIO1                      1003
#define IDS_BITCOUNT_4                  1004
#define IDC_RADIO2                      1004
#define IDS_BITCOUNT_8                  1005
#define IDC_CM                          1005
#define IDC_RADIO3                      1005
#define IDS_BITCOUNT_24                 1006
#define IDC_INCH                        1006
#define IDC_RADIO4                      1006
#define IDC_STATIC_FILENAME             1006
#define IDC_PEN_WIDTH                   1007
#define IDC_PIXEL                       1007
#define IDC_SCROLLBAR1                  1007
#define IDC_STATIC_PAGENUM              1007
#define IDC_PEN_COLOR                   1008
#define IDC_WIDTH                       1008
#define IDC_SCROLLBAR2                  1008
#define IDC_FILL_COLOR                  1009
#define IDC_PROPORTIONAL                1009
#define IDC_SCROLLBAR3                  1009
#define IDC_FONT                        1010
#define IDC_NAME1                       1010
#define IDC_RADIO8                      1010
#define IDC_PEN_STYLE                   1011
#define IDC_NAME2                       1011
#define IDC_NAME3                       1012
#define IDS_ADJUSTSIZE                  1012
#define IDC_VALUE1                      1013
#define IDC_VALUE2                      1014
#define IDC_VALUE3                      1015
#define IDC_TOTAL_SPACE                 1016
#define IDC_BRIGHT                      1017
#define IDC_FREE_SPACE                  1017
#define IDC_CONTRAST                    1018
#define IDC_UL                          1022
#define IDC_UP                          1023
#define IDC_UR                          1024
#define IDC_LEFT                        1025
#define IDC_RADIO24                     1025
#define IDC_CENTER                      1026
#define IDC_RADIO_DIB                   1027
#define IDC_RIGHT                       1027
#define IDC_RADIO_BITMAP                1028
#define IDC_DL                          1028
#define IDC_RADIO_PALETTE               1029
#define IDC_DOWN                        1029
#define IDC_COLORBITS                   1029
#define IDC_DR                          1030
#define IDC_SLIDER1                     1030
#define IDC_VALUE                       1031
#define IDC_COLORTABLE_BASE             2000
#define IDM_PIXEL                       32771
#define IDM_INCH                        32772
#define IDM_MM                          32773
#define IDM_SELECT                      32774
#define IDM_VMIRROR                     32775
#define IDM_FREELINE                    32776
#define IDM_RECT_F                      32777
#define IDM_ELLIPSE_F                   32778
#define IDM_FILL                        32779
#define IDM_MEDIANFILTER                32780
#define IDM_CORRECTGAMMA                32781
#define IDM_NEGATIVE                    32782
#define IDM_ROTATE90                    32783
#define IDM_EXPOSURE                    32783
#define IDM_ROTATE180                   32784
#define IDM_ROTATE270                   32785
#define IDM_FLIP_H                      32786
#define IDM_HOMOEDGEDETECT              32786
#define IDM_HMIRROR                     32787
#define IDM_SCALE                       32788
#define IDM_VERT                        32789
#define IDM_HORZ                        32790
#define IDM_VERTHORZ                    32791
#define IDM_LAP1                        32792
#define IDM_LAP2                        32793
#define IDM_LAP3                        32794
#define IDM_LAP4                        32795
#define IDM_SOBEL                       32796
#define IDM_HOUGH                       32797
#define IDM_ROTATE                      32798
#define IDM_POINT                       32810
#define IDM_GRAY                        32812
#define IDM_ADJUSTCOLOR                 32813
#define IDM_PAINTTOOL                   32815
#define IDM_PW_1                        32816
#define IDM_PW_2                        32818
#define IDM_PW_3                        32819
#define IDM_CANVASSIZE                  32820
#define IDM_BC                          32821
#define IDM_PW_4                        32822
#define IDM_PW_5                        32823
#define IDM_PW_6                        32824
#define IDM_COLORBITS                   32825
#define IDM_PW_7                        32826
#define IDM_PW_8                        32827
#define IDM_PW_OTHER                    32828
#define IDM_SOLID                       32829
#define IDM_DASH                        32830
#define IDM_DOT                         32831
#define IDM_PENCOLOR                    32832
#define IDM_SELECTPASTE                 32833
#define IDM_ROUNDRECT_H                 32834
#define IDM_FILLCOLOR                   32835
#define IDM_PENWIDTH                    32836
#define IDM_ROUNDRECT_F                 32837
#define IDM_LINE                        32838
#define IDM_RECT_H                      32839
#define IDM_ELLIPSE_H                   32840
#define IDM_TEXT                        32841
#define IDM_PAINTPARAM                  32842
#define IDM_FONT                        32843
#define IDM_HF1                         32844
#define IDM_HF2                         32845
#define IDM_HF3                         32846
#define IDM_LF1                         32847
#define IDM_LF2                         32848
#define IDM_LF3                         32849
#define IDM_NORTH                       32850
#define IDM_NORTHEAST                   32851
#define IDM_EAST                        32852
#define IDM_SOUTHEAST                   32853
#define IDM_SOUTH                       32854
#define IDM_SOUTHWEST                   32855
#define IDM_WEST                        32856
#define IDM_NORTHWEST                   32857
#define IDM_CROP                        32858
#define IDM_CURVE                       32859
#define IDM_LEFT                        32860
#define IDM_CENTER                      32861
#define IDM_RIGHT                       32862
#define IDM_TEXTTOOL                    32863
#define IDM_COPYTO                      32868
#define IDM_PASTEFROM                   32869
#define IDM_RED                         32871
#define IDM_BLUE                        32872
#define IDM_GREEN                       32873
#define IDM_GETRED                      32874
#define IDM_GETGREEN                    32875
#define IDM_GETBLUE                     32876
#define IDM_PASTEASFILE                 32877
#define IDM_ERASER                      32878
#define IDM_PICKER                      32880
#define IDM_DIFFERENCEEDGEDETECT        32883
#define IDM_SOBELED                     32884
#define IDM_HOUGHED                     32885
#define IDM_EMBOSSMENT                  32886
#define IDM_SPREAD                      32887
#define IDM_CANNYED                     32888
#define IDM_ROTATE_ANGLE                32891
#define IDM_EROSION_H                   32895
#define IDM_EROSION_V                   32896
#define IDM_DILATION_H                  32897
#define IDM_DILATION_V                  32898
#define IDM_CLOSE_H                     32899
#define IDM_CLOSE_V                     32900
#define IDM_OPEN_H                      32901
#define IDM_OPEN_V                      32902
#define IDM_THIN                        32903
#define IDM_REVERSE                     32904
#define IDM_FFT                         32905
#define IDM_DCT                         32906
#define IDM_WALH                        32907
#define IDM_CONTOUR_H                   32908
#define IDM_CONTOUR_V                   32909

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32889
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
